<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose_ui-multiselect-trigger-icon ui-_8f5c02</name>
   <tag></tag>
   <elementGuidId>13c778b3-f2cc-454d-875a-9430b0a96cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div[6]/div/div/div/roots-multiselect/div/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-multiselect-trigger-icon.ui-clickable.ng-tns-c54-68.fas.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>71cc0bbd-6c36-4f83-9d8e-fc6a21a24eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-multiselect-trigger-icon ui-clickable ng-tns-c54-68 fas fa-angle-down</value>
      <webElementGuid>352c471d-5d8e-4641-9d73-f85eaa921ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[@class=&quot;bg-E3E3E3&quot;]/app-case360[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-9 mb-3 mb-lg-0 pl-lg-0 pl-xl-0&quot;]/div[@class=&quot;clearfix h-100 bg-white&quot;]/app-case360-activity[@class=&quot;ng-star-inserted&quot;]/roots-dialog[@class=&quot;ng-tns-c52-42 ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c52-42 col-xl-8 col-lg-8 col-md-8 px-0 ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-dialog-draggable ui-dialog-resizable ng-star-inserted&quot;]/div[@class=&quot;ui-dialog-content ui-widget-content ng-tns-c52-42&quot;]/app-usertask[@class=&quot;ng-tns-c52-42 ng-star-inserted&quot;]/form[@class=&quot;ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;form-group&quot;]/roots-multiselect[@class=&quot;roots-form-control ng-tns-c54-68 ui-inputwrapper-filled ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c54-68 ui-multiselect ui-widget ui-state-default ui-corner-all&quot;]/div[@class=&quot;ng-tns-c54-68 ui-multiselect-trigger ui-state-default ui-corner-right&quot;]/span[@class=&quot;ui-multiselect-trigger-icon ui-clickable ng-tns-c54-68 fas fa-angle-down&quot;]</value>
      <webElementGuid>ada2bdc9-f6b0-4469-953b-1fab9d49551d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div[6]/div/div/div/roots-multiselect/div/div[3]/span</value>
      <webElementGuid>4df24de3-b7b1-4812-bf95-b701d0d027ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/roots-multiselect/div/div[3]/span</value>
      <webElementGuid>ff671407-ed9c-472e-a1d0-df1136a75884</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
