<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_balya MR., pradeep kumar</name>
   <tag></tag>
   <elementGuidId>1756dedb-6752-4086-acd1-f4a493bdf6a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-26-label']/div/div/div[2]/roots-table/div/div/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61e97f07-d8a8-4222-879e-0ecab5b56ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary ng-star-inserted</value>
      <webElementGuid>1de04f77-60d2-4ff0-9480-ea9da8a82c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/home/participant/5518</value>
      <webElementGuid>ef33152a-c245-4fc0-a379-4b595336dde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>balya MR., pradeep kumar </value>
      <webElementGuid>5de41542-7d37-4191-907e-32ceec5d2a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-26&quot;)/div[@id=&quot;ui-panel-26-label&quot;]/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c76-95&quot;]/div[@class=&quot;clearfix ng-tns-c76-95&quot;]/div[@class=&quot;app-tabview bg-white&quot;]/roots-table[1]/div[@class=&quot;ui-table ui-widget&quot;]/div[@class=&quot;ui-table-wrapper ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted activeRow&quot;]/td[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;text-primary ng-star-inserted&quot;]</value>
      <webElementGuid>844f3a31-0f18-4187-b767-28959d22d690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-26-label']/div/div/div[2]/roots-table/div/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>650055d3-bdc5-400f-92de-b543802f4dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'balya MR., pradeep kumar')]</value>
      <webElementGuid>c5a74834-1b3a-49eb-afd0-1c259d708d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name:'])[1]/following::a[1]</value>
      <webElementGuid>eaf794d9-6816-4fdf-b1fc-c5b0b3f88fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Defendant-1'])[1]/following::a[1]</value>
      <webElementGuid>c5c55f41-1428-4199-97fb-e09dcf7041a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attorney:'])[1]/preceding::a[1]</value>
      <webElementGuid>beaff9b0-e2c0-4966-8ab1-c0651d109aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[11]/preceding::a[1]</value>
      <webElementGuid>4f21065f-e3b4-4f1e-961c-710a5cf89f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='balya MR., pradeep kumar']/parent::*</value>
      <webElementGuid>412ed4cb-4cf8-4df7-8102-7a0cdffb401c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/home/participant/5518')])[2]</value>
      <webElementGuid>cbc86b9d-7aa2-458d-9be5-bf27a2a5a7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>5b375367-c888-46ba-9b4a-73dfc2078cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/home/participant/5518' and (text() = 'balya MR., pradeep kumar ' or . = 'balya MR., pradeep kumar ')]</value>
      <webElementGuid>b39ae9eb-3138-41bd-889e-387ef0f530a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
