<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Case Created Successfully</name>
   <tag></tag>
   <elementGuidId>779c6501-dd0f-4489-b6ef-01b5ea2645f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'Intake' or . = 'Intake')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-toast-summary.ng-tns-c67-187</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8049b346-9459-4f80-b543-995a3763da54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-toast-summary ng-tns-c67-187</value>
      <webElementGuid>62d9e7b8-c82b-4863-910e-738612202366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intake</value>
      <webElementGuid>d7166807-9519-43c5-b098-26e6d249b759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;bg-E3E3E3&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/roots-toast[@class=&quot;ng-tns-c68-4 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c68-4 ui-toast ui-widget ui-toast-top-right&quot;]/roots-toastitem[@class=&quot;ng-tns-c67-187 ng-trigger ng-trigger-toastAnimation ng-tns-c68-4 ng-star-inserted&quot;]/div[@class=&quot;ui-toast-message ui-shadow ng-tns-c67-187 ng-trigger ng-trigger-messageState ui-toast-message-success&quot;]/div[@class=&quot;ui-toast-message-content ng-tns-c67-187&quot;]/div[@class=&quot;ui-toast-message-text-content ng-tns-c67-187 ng-star-inserted&quot;]/div[@class=&quot;ui-toast-summary ng-tns-c67-187&quot;]</value>
      <webElementGuid>7e8b537e-1215-4ab7-9849-4b737c837ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advance Filter'])[1]/following::div[9]</value>
      <webElementGuid>725a7004-a99c-467a-af74-5af88eb40fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='label for searchText'])[2]/following::div[9]</value>
      <webElementGuid>1808cdbe-4a03-4e62-a6fe-a61eea466294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::div[2]</value>
      <webElementGuid>795f524d-3f21-4541-89be-9f10bce7937d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Intake']/parent::*</value>
      <webElementGuid>ef3513a2-fc3a-46ae-b222-0b288951cd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roots-toastitem/div/div/div/div</value>
      <webElementGuid>7be1aea2-7896-4b4f-972a-8d11b727aea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Intake' or . = 'Intake')]</value>
      <webElementGuid>b8290a29-7cf2-4664-a84a-eea02c0e1937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
