<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_Note</name>
   <tag></tag>
   <elementGuidId>e8f49f00-dc82-42dd-bf2b-10dbcad67712</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='Note'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5651e0f7-19eb-47a9-babc-324359db17bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b125124b-cf56-4412-833d-42d6b6b7ded3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>83737e26-4105-483d-8db1-4363b2145606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>6652524b-81f8-44c3-903e-c5fff26abf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>f43a993b-759f-46e8-8fae-b0e2e7a3196b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>fc013c8a-cfd6-4b93-96d6-9de966ebb51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>880d28bc-3428-42ba-ab30-4d83374ccd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Note&quot;)</value>
      <webElementGuid>fa75fab7-81f5-4a02-b308-aa6452f20d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Note']</value>
      <webElementGuid>b3d177b6-0d02-4148-8779-828617317626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/form/div/div/div[2]/div[3]/app-attachment/div/roots-dialog/div/div[2]/app-add-dms-attachment-form/form/div/div/div[4]/div/textarea</value>
      <webElementGuid>588e75de-9c41-4d6f-825c-1747486b59d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/textarea</value>
      <webElementGuid>6edfb900-274b-4dc1-a349-b5a3a931b828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Note']</value>
      <webElementGuid>8fedfa0a-9ade-4fd2-806a-f702fc5a1d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
